title: "Azure PaaS Hands on Lab"
description: This hand-on-lab will guide you through creating an application using various Azure PaaS services.
theme: just-the-docs

#url: https://just-the-docs.github.io

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
